# Generated by Django 4.2.18 on 2025-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_mycustomproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
