# Generated by Django 4.2.18 on 2025-01-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_mycustomproduct_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCustomProduct',
        ),
    ]
